ALTER SESSION SET nls_date_format = 'DD-MM-YY';
DROP TABLE ticker;

CREATE TABLE ticker (
        SYMBOL VARCHAR2(10), 
        tstamp DATE, 
        price NUMBER);

INSERT INTO ticker VALUES('ACME', '01-04-23', 12);
INSERT INTO ticker VALUES('GLOBEX', '17-04-23', 8);
INSERT INTO ticker VALUES('GLOBEX', '01-04-23', 11);
INSERT INTO ticker VALUES('OSCORP', '20-04-23', 9);
INSERT INTO ticker VALUES('ACME', '02-04-23', 17);
INSERT INTO ticker VALUES('OSCORP', '19-04-23', 23);
INSERT INTO ticker VALUES('ACME', '03-04-23', 19);
INSERT INTO ticker VALUES('GLOBEX', '03-04-23', 13);
INSERT INTO ticker VALUES('OSCORP', '18-04-23', 12);
INSERT INTO ticker VALUES('GLOBEX', '02-04-23', 12);
INSERT INTO ticker VALUES('ACME', '04-04-23', 21);
INSERT INTO ticker VALUES('GLOBEX', '04-04-23', 12);
INSERT INTO ticker VALUES('OSCORP', '17-04-23', 14);
INSERT INTO ticker VALUES('OSCORP', '15-04-23', 12);
INSERT INTO ticker VALUES('OSCORP', '14-04-23', 15);
INSERT INTO ticker VALUES('OSCORP', '16-04-23', 16);
INSERT INTO ticker VALUES('ACME', '05-04-23', 25);
INSERT INTO ticker VALUES('GLOBEX', '05-04-23', 23);
INSERT INTO ticker VALUES('ACME', '06-04-23', 12);
INSERT INTO ticker VALUES('GLOBEX', '06-04-23', 10);
INSERT INTO ticker VALUES('ACME', '07-04-23', 15);
INSERT INTO ticker VALUES('GLOBEX', '07-04-23', 9);
INSERT INTO ticker VALUES('GLOBEX', '08-04-23', 8);
INSERT INTO ticker VALUES('ACME', '08-04-23', 20);
INSERT INTO ticker VALUES('OSCORP', '13-04-23', 23);
INSERT INTO ticker VALUES('ACME', '13-04-23', 25);
INSERT INTO ticker VALUES('ACME', '10-04-23', 25);
INSERT INTO ticker VALUES('ACME', '23-04-23', 19);
INSERT INTO ticker VALUES('ACME', '09-04-23', 24);
INSERT INTO ticker VALUES('GLOBEX', '09-04-23', 9);
INSERT INTO ticker VALUES('OSCORP', '12-04-23', 12);
INSERT INTO ticker VALUES('GLOBEX', '10-04-23', 9);
INSERT INTO ticker VALUES('OSCORP', '23-04-23', 15);
INSERT INTO ticker VALUES('GLOBEX', '23-04-23', 9);
INSERT INTO ticker VALUES('OSCORP', '10-04-23', 15);
INSERT INTO ticker VALUES('ACME', '12-04-23', 15);
INSERT INTO ticker VALUES('GLOBEX', '12-04-23', 9);
INSERT INTO ticker VALUES('OSCORP', '09-04-23', 16);
INSERT INTO ticker VALUES('GLOBEX', '13-04-23', 10);
INSERT INTO ticker VALUES('OSCORP', '08-04-23', 20);
INSERT INTO ticker VALUES('ACME', '14-04-23', 25);
INSERT INTO ticker VALUES('GLOBEX', '14-04-23', 23);
INSERT INTO ticker VALUES('OSCORP', '07-04-23', 17);
INSERT INTO ticker VALUES('OSCORP', '06-04-23', 20);
INSERT INTO ticker VALUES('ACME', '15-04-23', 14);
INSERT INTO ticker VALUES('GLOBEX', '15-04-23', 12);
INSERT INTO ticker VALUES('ACME', '17-04-23', 14);
INSERT INTO ticker VALUES('ACME', '16-04-23', 12);
INSERT INTO ticker VALUES('GLOBEX', '16-04-23', 23);
INSERT INTO ticker VALUES('OSCORP', '05-04-23', 17);
INSERT INTO ticker VALUES('ACME', '18-04-23', 24);
INSERT INTO ticker VALUES('GLOBEX', '18-04-23', 7);
INSERT INTO ticker VALUES('OSCORP', '04-04-23', 18);
INSERT INTO ticker VALUES('OSCORP', '03-04-23', 19);
INSERT INTO ticker VALUES('ACME', '19-04-23', 23);
INSERT INTO ticker VALUES('GLOBEX', '19-04-23', 5);
INSERT INTO ticker VALUES('OSCORP', '02-04-23', 22);
INSERT INTO ticker VALUES('ACME', '20-04-23', 22);
INSERT INTO ticker VALUES('GLOBEX', '20-04-23', 3);
INSERT INTO ticker VALUES('OSCORP', '01-04-23', 22);

commit;


SELECT *
FROM Ticker 
MATCH_RECOGNIZE (
 PARTITION BY symbol
 ORDER BY tstamp
 MEASURES 
  FIRST(UP1.tstamp) AS UP1,
  FIRST(UP2.tstamp) AS UP2,
  FIRST(UP3.tstamp) AS UP3
 ONE ROW PER MATCH
 AFTER MATCH SKIP PAST LAST ROW
 PATTERN (STRT UP1+ DOWN+ UP2+ DOWN+ UP3+)
 DEFINE
  DOWN AS price < PREV(price),
  UP1 AS price > PREV(price),
  UP2 AS price > PREV(price) AND price > ALL(PREV(price),NEXT(price)),
  UP3 AS price > PREV(price)
) Ticker_Table
ORDER BY Ticker_Table.symbol, Ticker_Table.UP2;



SELECT *
FROM ticker 
MATCH_RECOGNIZE (
    PARTITION BY symbol
    ORDER BY tstamp
    MEASURES 
        FIRST(UP1.tstamp) AS UPTREND_START,
        FIRST(UP2.tstamp) AS UPTREND_END,
        FIRST(UP3.tstamp) AS DOWNTREND_START
    ONE ROW PER MATCH
    AFTER MATCH SKIP PAST LAST ROW
    PATTERN (UPTREND_START UPTREND+ DOWNTREND+ UPTREND_END)
    DEFINE
        DOWNTREND AS price < PREV(price),
        UPTREND AS price > PREV(price),
        UPTREND_START AS price > PREV(price),
        UPTREND_END AS price > PREV(price)
) TrendPatterns
ORDER BY TrendPatterns.stock_symbol, TrendPatterns.UPTREND_END;


SELECT *
FROM ticker 
MATCH_RECOGNIZE (
    PARTITION BY symbol
    ORDER BY tstamp
    MEASURES 
        FIRST(UP1.tstamp) AS UPTREND_START,
        LAST(UP2.tstamp) AS UPTREND_END,
        FIRST(DOWN1.tstamp) AS DOWNTREND_START
    ONE ROW PER MATCH
    AFTER MATCH SKIP PAST LAST ROW
    PATTERN (UPTREND_START UPTREND+ DOWNTREND+ UPTREND_END)
    DEFINE
        DOWNTREND AS DOWN1.price < PREV(DOWN1.price),
        UPTREND AS UP1.price > PREV(UP1.price),
        UPTREND_START AS UP1.price > PREV(UP1.price),
        UPTREND_END AS UP2.price > PREV(UP2.price)
) TrendPatterns
ORDER BY TrendPatterns.symbol, TrendPatterns.UPTREND_END;
