//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kursovoi_2023
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR()
        {
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
            this.ORDERTABLE = new HashSet<ORDERTABLE>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> IDSUPPLIER { get; set; }
        public string IMGSOURCE { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public string COLOR { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> CARRATING { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERTABLE> ORDERTABLE { get; set; }
    }
}
