//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kursovoi_2023
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> IDEQUIPMENTLIST { get; set; }
        public Nullable<decimal> IDCAR { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual EQUIPMENTLIST EQUIPMENTLIST { get; set; }
    }
}
