//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kursovoi_2023
{
    using System;
    
    public partial class GETALLORDERINFO_Result1
    {
        public decimal ID { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string DESCRIPTION { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> ISTESTDRIVE { get; set; }
        public Nullable<decimal> IDCAR { get; set; }
    }
}
