create database test3;

--------------------------------------------------------
--  File created - среда-декабря-13-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTS
--------------------------------------------------------

CREATE TABLE dbo.CLIENTS
(
    CLIENTID INT IDENTITY(1,1) PRIMARY KEY,
    FIRSTNAME NVARCHAR(50) NOT NULL,
    LASTNAME NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(100) UNIQUE NOT NULL,
    PHONENUMBER NVARCHAR(15),
    PASSWORD NVARCHAR(255) NOT NULL,
    ADDRESS NVARCHAR(200)
);

-- Вставка данных
INSERT INTO dbo.CLIENTS (FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, PASSWORD, ADDRESS)
VALUES 
    ('Иван', 'Иванов', 'ivan@example.com', '+71234567890', 'encryptedpassword1', 'Москва, ул. Ленина, 1'),
    ('Мария', 'Петрова', 'maria@example.com', '+71234567891', 'encryptedpassword2', 'Санкт-Петербург, пр. Невский, 2'),
    ('Влад', 'Владов', 'vlad@example.com', '+71234567890', 'encrypt123password1', 'Минск, ул. Ленина, 1');

-- Добавление ограничений
ALTER TABLE dbo.CLIENTS
    ALTER COLUMN CLIENTID INT NOT NULL;

ALTER TABLE dbo.CLIENTS
    ADD CONSTRAINT PK_CLIENTS PRIMARY KEY (CLIENTID);

ALTER TABLE dbo.CLIENTS
    ADD CONSTRAINT UQ_EMAIL UNIQUE (EMAIL);



-- DDL for Table CATEGORIES
CREATE TABLE dbo.CATEGORIES
(
    CATEGORYID INT IDENTITY(1,1) CONSTRAINT PK_CATEGORIES PRIMARY KEY,
    CATEGORYNAME NVARCHAR(100),
    PARENTID INT,
    NODELEVEL INT,
    NODEPATH NVARCHAR(400)
);

-- INSERT statements for CATEGORIES
INSERT INTO dbo.CATEGORIES (CATEGORYNAME, PARENTID, NODELEVEL, NODEPATH)
VALUES
    ('SUVs', NULL, 0, '/'),
    ('Convertibles', NULL, 0, '/'),
    ('Седан', NULL, NULL, NULL),
    ('Кроссовер', NULL, NULL, NULL),
    ('Хэтчбек', NULL, NULL, NULL);

-- Constraints for Table CATEGORIES
ALTER TABLE dbo.CATEGORIES ALTER COLUMN CATEGORYID INT NOT NULL;
ALTER TABLE dbo.CATEGORIES ALTER COLUMN CATEGORYNAME NVARCHAR(100) NOT NULL;

ALTER TABLE dbo.CATEGORIES
ADD CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORYID);

ALTER TABLE dbo.CATEGORIES
ADD CONSTRAINT CATEGORIES_PARENT_FK FOREIGN KEY (PARENTID)
REFERENCES dbo.[CATEGORIES] (CATEGORYID);





-- DDL for Table PRODUCTS
CREATE TABLE dbo.PRODUCTS
(
    PRODUCTID INT IDENTITY(1,1) CONSTRAINT PK_PRODUCTS PRIMARY KEY,
    CATEGORYID INT,
    PRODUCTNAME NVARCHAR(100),
    DESCRIPTION NVARCHAR(1000),
    PRICE DECIMAL(10,2),
    STOCKQUANTITY INT
);

-- INSERT statements for PRODUCTS
INSERT INTO dbo.PRODUCTS (CATEGORYID, PRODUCTNAME, DESCRIPTION, PRICE, STOCKQUANTITY)
VALUES
    (1, 'Toyota Camry', 'Седан, белого цвета, 2022 года выпуска', 2000000, 3),
    (2, 'Nissan Qashqai', 'Кроссовер, красного цвета, 2021 года выпуска', 1500000, 2),
    (3, 'Volkswagen Golf', 'Хэтчбек, синего цвета, 2020 года выпуска', 1400000, 4);

-- Constraints for Table PRODUCTS
ALTER TABLE dbo.PRODUCTS ALTER COLUMN PRODUCTID INT NOT NULL;
ALTER TABLE dbo.PRODUCTS ALTER COLUMN PRODUCTNAME NVARCHAR(100) NOT NULL;
ALTER TABLE dbo.PRODUCTS ALTER COLUMN PRICE DECIMAL(10,2) NOT NULL;
ALTER TABLE dbo.PRODUCTS ALTER COLUMN STOCKQUANTITY INT NOT NULL;

ALTER TABLE dbo.PRODUCTS
ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCTID);

ALTER TABLE dbo.PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORYID)
REFERENCES dbo.CATEGORIES (CATEGORYID);


-- DDL for Table ORDERS
CREATE TABLE dbo.ORDERS
(
    ORDERID INT IDENTITY(1,1) CONSTRAINT PK_ORDERS PRIMARY KEY,
    CLIENTID INT,
    ORDERDATE DATE,
    ORDERAMOUNT DECIMAL(10,2),
    EMPLOYEEID INT
);

-- INSERT statements for ORDERS
INSERT INTO dbo.ORDERS (CLIENTID, ORDERDATE, ORDERAMOUNT, EMPLOYEEID)
VALUES
    (1, '2023-10-04', 2000000, NULL),
    (2, '2023-10-04', 20000, NULL),
    (21, '2023-10-04', 400000, NULL),
    (21, '2023-02-02', 400000, NULL),
    (21, '2023-08-02', 400000, NULL),
    (21, '2022-10-02', 400000, NULL),
    (1, '2023-11-15', 2000000, NULL),
    (2, '2023-11-15', 20000, NULL),
    (21, '2023-11-15', 400000, NULL),
    (21, '2022-02-02', 400000, NULL),
    (21, '2023-08-02', 400000, NULL),
    (21, '2022-10-02', 400000, NULL),
    (1, '2023-01-01', 100, 1),
    (2, '2023-01-02', 150, 2),
    (2, '2023-01-02', 150, 2),
    (2, '2023-11-14', 120, 1),
    (2, '2023-11-15', 80, 2),
    (1, '2023-01-01', 100, 1);

-- Constraints for Table ORDERS
ALTER TABLE dbo.ORDERS ALTER COLUMN ORDERID INT NOT NULL;
ALTER TABLE dbo.ORDERS ALTER COLUMN ORDERDATE DATE NOT NULL;
ALTER TABLE dbo.ORDERS ALTER COLUMN ORDERAMOUNT DECIMAL(10,2) NOT NULL;









-- DDL for Table REVIEWS
CREATE TABLE dbo.REVIEWS
(
    REVIEWID INT IDENTITY(1,1) CONSTRAINT PK_REVIEWS PRIMARY KEY,
    PRODUCTID INT,
    CLIENTID INT,
    REVIEWTEXT NVARCHAR(1000),
    RATING INT CHECK (RATING BETWEEN 1 AND 5)
);

-- INSERT statements for REVIEWS
INSERT INTO dbo.REVIEWS (PRODUCTID, CLIENTID, REVIEWTEXT, RATING)
VALUES
    (1, 1, 'Отличный автомобиль, очень доволен покупкой!', 5);

-- Constraints for Table REVIEWS
ALTER TABLE dbo.REVIEWS ALTER COLUMN REVIEWID INT NOT NULL;
ALTER TABLE dbo.REVIEWS ALTER COLUMN REVIEWTEXT NVARCHAR(1000) NOT NULL;

ALTER TABLE dbo.REVIEWS
ADD CONSTRAINT PK_REVIEWS PRIMARY KEY (REVIEWID);

ALTER TABLE dbo.REVIEWS
ADD CONSTRAINT FK_REVIEWS_PRODUCTS FOREIGN KEY (PRODUCTID)
REFERENCES dbo.PRODUCTS (PRODUCTID);

ALTER TABLE dbo.REVIEWS
ADD CONSTRAINT FK_REVIEWS_CLIENTS FOREIGN KEY (CLIENTID)
REFERENCES dbo.CLIENTS (CLIENTID);




-- DDL for Table ORDEREDPRODUCTS
CREATE TABLE dbo.ORDEREDPRODUCTS
(
    ORDERID INT,
    PRODUCTID INT,
    QUANTITY INT NOT NULL,
    TOTALCOST DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_ORDEREDPRODUCTS PRIMARY KEY (ORDERID, PRODUCTID)
);

-- INSERT statements for ORDEREDPRODUCTS
INSERT INTO dbo.ORDEREDPRODUCTS (ORDERID, PRODUCTID, QUANTITY, TOTALCOST)
VALUES
    (1, 1, 1, 2000000),
    (21, 2, 1, 20000),
    (23, 3, 2, 800000);

-- Constraints for Table ORDEREDPRODUCTS
ALTER TABLE dbo.ORDEREDPRODUCTS
ADD CONSTRAINT FK_ORDEREDPRODUCTS_ORDERS FOREIGN KEY (ORDERID)
REFERENCES dbo.ORDERS (ORDERID);

ALTER TABLE dbo.ORDEREDPRODUCTS
ADD CONSTRAINT FK_ORDEREDPRODUCTS_PRODUCTS FOREIGN KEY (PRODUCTID)
REFERENCES dbo.PRODUCTS (PRODUCTID);




select * from CLIENTS;
select * from CATEGORIES;
select * from PRODUCTS;
select * from ORDERS;
select * from REVIEWS;
select * from ORDEREDPRODUCTS;