// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyAA_sE-e-YroFyffVOTDv5m-fGIK-P4-sQ',
  //   appId: '1:179082997255:android:e5b7f8fdb25dfb027f44a2',
  //   messagingSenderId: '179082997255',
  //   projectId: 'lab11-d295f',
  //   storageBucket: 'lab11-d295f.firebasestorage.app',
  // );

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAA_sE-e-YroFyffVOTDv5m-fGIK-P4-sQ',
  appId: '1:179082997255:android:c53de54e11d47b4d7f44a2',
  messagingSenderId: '179082997255',
  projectId: 'lab11-d295f',
  storageBucket: 'lab11-d295f.firebasestorage.app',
);

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfq6UHZWatX0rqkQfE8mgiJWiGTSMWFj8',
    appId: '1:179082997255:web:2f6433532f5496277f44a2',
    messagingSenderId: '179082997255',
    projectId: 'lab11-d295f',
    authDomain: 'lab11-d295f.firebaseapp.com',
    storageBucket: 'lab11-d295f.firebasestorage.app',
    measurementId: 'G-4BNJP0VTZP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBAVBjnYH-jQj_ihNS4yiQZHxrrddqqE',
    appId: '1:179082997255:ios:9519117e314380147f44a2',
    messagingSenderId: '179082997255',
    projectId: 'lab11-d295f',
    storageBucket: 'lab11-d295f.firebasestorage.app',
    iosBundleId: 'com.example.lab11Test1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBAVBjnYH-jQj_ihNS4yiQZHxrrddqqE',
    appId: '1:179082997255:ios:9519117e314380147f44a2',
    messagingSenderId: '179082997255',
    projectId: 'lab11-d295f',
    storageBucket: 'lab11-d295f.firebasestorage.app',
    iosBundleId: 'com.example.lab11Test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfq6UHZWatX0rqkQfE8mgiJWiGTSMWFj8',
    appId: '1:179082997255:web:450007ff50427c497f44a2',
    messagingSenderId: '179082997255',
    projectId: 'lab11-d295f',
    authDomain: 'lab11-d295f.firebaseapp.com',
    storageBucket: 'lab11-d295f.firebasestorage.app',
    measurementId: 'G-HL5K5GBGY6',
  );

}